# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'jizhang' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jizhang

  pod 'Masonry', '~> 1.1.0'
  pod 'IQKeyboardManager', '~> 5.0.7’
  pod 'PNChart', '~> 0.8.9'

  pod 'AFNetworking', '~> 3.1.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'MJRefresh', '~> 3.1.15.3'

#pod 'SVProgressHUD','~> 2.1.2’


#pod 'YYModel', '~> 1.0.4'
#pod 'SDWebImage', '~> 4.2.3'

#pod 'TTTAttributedLabel','~> 2.0.0’
#pod 'JPush', '3.0.2'
#自动侧或返回
#  pod 'FDFullscreenPopGesture','~> 1.1’

end
